AY2425S1-CS2103T-F09-2/tp

- docs/AboutUs.md
This PR addresses issue #18 by removing the dummy information from the "About Us" section.
- Removed placeholder text and replaced it with updated content in the "AboutUs" section.
Closes #18
Please review and let me know if any further modifications are needed.
> Add Brian's information to AboutUs

- docs/AboutUs.md
> Update about us page with chuajunyu's info

- docs/AboutUs.md
> Update AboutUs page with Shaoheng's info

- docs/AboutUs.md
- docs/index.md
> Update the link of the GitHub Actions build status badge

- docs/DeveloperGuide.md
Fixes #38 , adds currently identified non functional requirements to the developer guide
> Add NFR to DeveloperGuide

- docs/DeveloperGuide.md
This PR updates the glossary as required.
- Updated docs/DeveloperGuide.md to include newly included terms in user guide
#40 
Let me know if any further changes are needed.
> Update Glossary Terms

- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/model/person/PersonTest.java
Implement duplicate contact handling based on the following criteria:
Two contacts are considered duplicates if any one of the following criteria holds true
- They have the exact same phone number
- They have the exact same email
Having the same name alone is not enough to be classified as a duplicate.
Fixes #58
> Implement duplicate contact handling

- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/role/RoleHandler.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/role/RoleHandlerTest.java
> 59 implement parser for role tag

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
For #56 #68 
Fixed the test cases to account for telegram username in Person class on AddCommand and EditCommand.
All existing test cases now pass.
> Fix failing test cases from telegram username

- build.gradle
- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/MainWindow.fxml
> Update app name and user guide links

- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/CommandBuffer.java
- src/test/java/seedu/address/ui/CommandBufferTest.java
Created a working command buffer with test cases that allows you to cycle through previously executed commands within the same session. 
Also added test cases
> 83 add command buffer

- src/main/java/seedu/address/model/event/Event.java
- src/test/java/seedu/address/model/event/EventTest.java
For #87  Adds the Event Class implementation:
Event Class has 4 Sets, one for each Role type. Sets are to be empty in case where event has no persons for corresponding role.
Each set can be used in generating the JsonAdaptedEvent for storage
Things to consider:
Accessing events, should events be accessed through a unique ID or by index in a list?
> Event Class Skeleton

- src/main/java/seedu/address/logic/commands/event/commands/DeleteEventCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/event/parser/DeleteEventCommandParser.java
- src/main/java/seedu/address/logic/parser/event/parser/ViewEventCommandParser.java
- src/test/java/seedu/address/logic/commands/event/commands/DeleteEventCommandTest.java
- src/test/java/seedu/address/logic/commands/event/commands/ViewEventCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/event/parser/DeleteEventCommandParserTest.java
- src/test/java/seedu/address/logic/parser/event/parser/ViewEventCommandParserTest.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
Allows deleting of events with `erase EVENT INDEX`
closes #159
> Add delete events functionality

- src/main/java/seedu/address/logic/commands/contact/commands/AddCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/contact/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/contact/commands/AddCommandTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
Closes #144 
Will specify which field is duplicated
If multiple fields are duplicated will specify the first field in the following order:
- Phone
- Email
- Telegram
> Specify Duplicated Field

- src/main/java/seedu/address/logic/commands/contact/commands/ClearCommand.java
- src/main/java/seedu/address/model/event/Event.java
- src/main/java/seedu/address/model/event/EventManager.java
Update the events UI panel to reflect changes on clear command
Fixes #134
> Update events UI on clear command

- src/main/java/seedu/address/ui/PersonCard.java
> Fix UI bug

- src/main/java/seedu/address/logic/commands/contact/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/contact/parser/AddCommandParser.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/TelegramUsername.java
- src/test/java/seedu/address/logic/parser/contact/parser/AddCommandParserTest.java
> Bug fix for email capitalisation, telegram handle message and add contact failure

- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/contact/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommandTest.java
- src/test/java/seedu/address/logic/parser/SearchModeSearchCommandParserTest.java
- src/test/java/seedu/address/logic/parser/contact/parser/EditCommandParserTest.java
- src/test/java/seedu/address/model/event/EventTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/predicates/PersonIsRolePredicateTest.java
- src/test/java/seedu/address/model/role/RoleHandlerTest.java
- src/test/java/seedu/address/storage/JsonAdaptedRoleTest.java
The constants defined for tests are sometimes not used in the tests. This PR will utilise these constants as much as possible, promoting good abstraction practices.
Fixes #208
> Improve constant abstractions

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/UiManager.java
- src/main/resources/view/BrownTheme.css
- src/main/resources/view/EventListPanel.fxml
- src/main/resources/view/Extensions.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ResultDisplay.fxml
Change the DarkTheme.css file to BrownTheme.css and rounded the borders of the boxes. Feel free to change the colours
> Change ui theme

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java
- src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
- src/main/java/seedu/address/logic/commands/searchmode/ClearExcludedCommand.java
- src/main/java/seedu/address/logic/commands/searchmode/ExcludePersonCommand.java
- src/main/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ExcludePersonCommandParser.java
- src/main/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParser.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/test/java/seedu/address/logic/commands/searchmode/CheckExcludedCommandTest.java
- src/test/java/seedu/address/logic/commands/searchmode/ClearExcludedCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ExcludePersonCommandParserTest.java
- src/test/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParserTest.java
Closes #217 Closes #215 
Change various error messages as well as moved the searchmode error message to Messages
> Error messages

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
- src/main/java/seedu/address/model/person/PersonInEventPredicate.java
Changes  RemoveFromEvent to check if last predicate was viewing an event and removed from the last viewed event.
Closes #222
> RemoveFromEvent Updates UI if removed from currently viewed event

- docs/UserGuide.md
Change description in summary of UG
> Change pi to ci in UG Command Summary

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/BrownTheme.css
Changed Ui on searchmode by adding a header for search results, changing the border to surround the middle panel and highlighting the command box
Additionally, the colors of the event card and person card are changed to make them more visually appealing.
> Change UI on searchmode

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/contact/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/contact/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/contact/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/contact/commands/FindNameCommand.java
- src/main/java/seedu/address/logic/commands/contact/commands/FindRoleCommand.java
- src/main/java/seedu/address/logic/commands/contact/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/event/commands/AddEventCommand.java
- src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java
- src/main/java/seedu/address/logic/commands/event/commands/EventAddAllCommand.java
- src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java
- src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
- src/main/java/seedu/address/logic/commands/searchmode/ExcludePersonCommand.java
Update error messages to be consistent with using contacts instead of persons
> Update error msgs

- src/main/resources/view/HelpWindow.css
Fixes #213 
Update help window to be of the same theme as rest of app
> Update help window theme

- docs/UserGuide.md
Closes #283 , Closes #250 and Closes #246
Changes UG description of search functions to better match the implementation.
> Change phrasing and add example for search functions

- docs/DeveloperGuide.md
Closes #253 and also #276 
Unsure if #276 counts as an enhancement or a new feature
> Adds Planned Enhancements to DG

- src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
- src/test/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommandTest.java
Closes #303 , Closes #301 
Changes the index validation in RemoveFromEvent and removes person from all roles instead of just 1
> Makes removePersonFromEvent remove completely and fixes bug with index validation checking

- docs/UserGuide.md
Adjust the formatting for the note boxes
> Adjust UG formatting

- src/test/java/seedu/address/model/person/AddressTest.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/person/TelegramUsernameTest.java
Tests for Persons were not comprehensive. This PR will ensure more test cases are added.
Closes #317
> Fix tests for Person

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java
Reverts AY2425S1-CS2103T-F09-2/tp#315
> Revert "Change command name for adding event"

- src/test/java/seedu/address/model/event/EventListTest.java
- src/test/java/seedu/address/model/event/EventManagerTest.java
- src/test/java/seedu/address/model/event/EventTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
The test coverage in EventListTest, EventManagerTest and EventTest have been improved.
Fixes #322
> Improve event related tests

- src/main/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParser.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/contact/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/event/parser/NewEventCommandParserTest.java
- src/test/java/seedu/address/logic/parser/event/parser/RemovePersonFromEventParserTest.java
The PR updates the parser tests to be more comprehensive.
Fixes #325
> Update all parser tests to improve code coverage

- src/main/java/seedu/address/logic/commands/contact/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/HelpCommandTest.java
- src/test/java/seedu/address/logic/commands/contact/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/ExcludePersonCommandParserTest.java
- src/test/java/seedu/address/model/person/AddressTest.java
- src/test/java/seedu/address/model/person/EmailTest.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/person/PersonInEventPredicateTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
- src/test/java/seedu/address/model/person/TelegramUsernameTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
- src/test/java/seedu/address/model/predicates/EmailContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/predicates/PersonIsRolePredicateTest.java
- src/test/java/seedu/address/model/predicates/PhoneNumberContainsKeywordPredicateTest.java
- src/test/java/seedu/address/model/predicates/TelegramContainsKeywordPredicateTest.java
This PR extends east coverage to the entire code base.
Fixes #339
> Extend test coverage for entire codebase

- docs/SettingUp.md
Edited Settingup.md page Closes #352
> Remove tutorial links and change name

- docs/DeveloperGuide.md
> Add input field length enhancement

- docs/DeveloperGuide.md
Remove some placeholder text in Dev Guide
> Remove placeholder texts

- docs/DeveloperGuide.md
> Increase diagram size

- src/main/java/seedu/address/MainApp.java
> Update version to v1.6
