README.md, docs/index.md
This PR addresses issue #31 by removing the dummy placeholder information from the "About Us" section, and preparing it to reflect the actual context of the project.
- Removed dummy text from the AboutUs component.
- Updated the AboutUs section to better reflect the project description and user profile.
=> Include PlanPal information in readme

src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/TelegramUsername.java, src/test/java/seedu/address/model/person/TelegramUsernameTest.java
Closes #55 
A telegram username is valid if:
- is between 5 and 32 characters
- Starts with an alphabet
- Only contains alphanumeric characters and underscore
A telegram username is equal if
- The strings are equal, ignoring case.
Concern:
- `.hashCode()` function generates hashcodes based on the string, and this is case sensitive. Hence, 2 telegram usernames which might be equal by the `.equal()` function might not give the same `.hashCode()`. 
- I didn't change this for now since I am not sure what `.hashCode()` is being used for and what a desired effect might be
=> Add TelegramUsername class and test file

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Duplicate handling has only been implemented for the "Add Person" function, but not the "Edit Person function"
As such, it is possible to edit a person to have the same email and/or phone number as another person. If duplicates are left to exist, the app will crash on next launch.
Fixes #72
This prevents the creation of multiple records of same phone number or email in the database.
=> Fix duplicate handling in Edit Person command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/storage/JsonAdaptedRoleTest.java
Roles are rendered with the same colour, which may be too boring.
This PR will allow rendering of different role labels with different colours to improve the GUI.
Furthermore, some small bug fixes like correcting the addCommand instruction message and removing unused tag fields were made.
=> Add colours to roles

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/TelegramUsername.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/TelegramUsernameTest.java
Fix #79
- Null Telegram Usernames are still equal to other Null Telegram Usernames. This might seem unintuitive:
- 1.  Because `equals` recognise null usernames to be different could help us in implementing uniqueness in persons when they both have no telegram username. 
- 2. And also because IRL, you can choose to have no telegram username, but still be a unique user on telegram
- However, this caused issues in certain test cases which relied on equality checking to check whether the parser is adding the same person (without a telegram username) 
- Additionally, a telegram username on it's own cannot enforce uniqueness, it's a weak notion of identity, so on it's own, even if it's null, it must still be tagged to a unique phone and email.
- Will check if both have telegram username, if …
=> Telegram username dupe handling

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Currently edit telegram username using t/ does not allow removal of telegram username as it will be marked as invalid input.
To keep in line with the ability to remove optional fields, adding the ability to remove telegram username on edit with empty t/ can be beneficial.
closes #92
=> Update edit telegram username

src/main/java/seedu/address/model/event/EventList.java, src/main/java/seedu/address/model/event/EventManager.java, src/main/java/seedu/address/model/event/ReadOnlyEventManager.java, src/main/java/seedu/address/model/event/exceptions/EventException.java, src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java, src/test/java/seedu/address/model/event/EventListTest.java, src/test/java/seedu/address/model/event/EventManagerTest.java
Fix #89 
Created a really basic EventManager class that abstracts away the work of handling many events at once, this is similar to what AddressBook class does when handling many Person classes.
This also implements an interface which provides an observableList object which is unmodifiable, which will be useful when implementing logic later on for the model and UI.
=> Init event manager class

build.gradle, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Fixes #88 
Unique ID is generated using java.util.UUID library which ensures that the chance of duplicate IDs is extremely small. The ID is currently not added to the Person constructor yet, unless necessary for future implementations, which means that each Person will have a different ID every time on start up and the ID is not fixed on initial adding of the person to the address book.
Side addition:
- Enabled assertions for this week's tasks
=> Add ID field to Person

src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/RemovePersonFromEventParser.java, src/main/java/seedu/address/model/event/Event.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/RemovePersonFromEventCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/RemovePersonFromEventParserTest.java, src/test/java/seedu/address/model/event/EventTest.java
For #108 
Adds `RemovePersonFromEventCommand` and `RemovePersonFromEventParser`
To remove a person from event: 
`remove ei/ [EventIndex] pi/ [PersonIndex]`
Changes to other classes:
- new prefixes in `CliSyntax`: 
- `ei`:event index
- `pi`: person index
- Event Class 
- new constructor `new Event(Event other)`
- Creates a copy of the event
- `String getRole(Person)`
- Gets string form of the role a person has in an event
- `Set<Person> getAllPersons()`
- Gets a Set<Person> with all Persons in a role for the event
=> Remove person from event

src/main/java/seedu/address/logic/commands/contact/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/EditCommand.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/EventManager.java, src/test/java/seedu/address/model/event/EventTest.java
Updated the logic for these commands execution, as it no longer makes sense to store UUID in EventStorage over the Person themselves. This is because the latter would require a major rework of the current implementation of the interactions between ModelManager and EventManager.
=> Update editCommand and deleteCommand logic

src/main/java/seedu/address/logic/commands/event/commands/ViewEventCommand.java, src/main/java/seedu/address/logic/parser/event/parser/ViewEventCommandParser.java, src/test/java/seedu/address/logic/commands/event/commands/ViewEventCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/event/parser/ViewEventCommandParserTest.java
Currently, the `view` command is implemented by typing the exact event name after the keyword. For example, one must type `view NUS Student Life Fair 2024` to view the details of an event titled "NUS Student Life Fair 2024".
In line with the rest of our commands, we wish to refer to events by index, i.e. `view 1` to view the event with ID 1.
This PR fixes this.
Fixes #171
=> Fix consistent format for View command

src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/event/commands/ViewEventCommand.java, src/main/java/seedu/address/logic/commands/searchmode/ExitSearchModeCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Fixes #177 #169 
Allows exiting of searchmode with "exit"
Changed commant to exit searchmode from "exitsearchmode" to "exitsearch"
Changed error msg from "Unknown Command" to display that the person is in command mode.
=> Refine searchmode

src/main/java/seedu/address/logic/commands/contact/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/EventManager.java, src/main/java/seedu/address/ui/EventCard.java, src/main/java/seedu/address/ui/EventListPanel.java, src/main/java/seedu/address/ui/Observer.java, src/main/resources/view/EventListCard.fxml, src/test/java/seedu/address/model/event/EventTest.java
Fixes #137 
Fixes #148 
1. Changed "event-add" to "eventadd" to become consistent with other command styles
2. Added an Observer pattern to have the UI be updated whenever contacts of an event changes
3. Added a total count to events to reflect total number of distinct contacts in events
=> Update Event Card UI to become reactive to contact changes

src/main/java/seedu/address/ui/CommandBox.java
This PR changes the behaviour of the app such that when a user enters a valid or invalid command, the search box will clear.
The user can then use the up and down arrow keys to scroll through the command history.
Closes #152
=> Clear command box after user enters a command even if invalid

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/EventAddAllCommand.java, src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java, src/main/java/seedu/address/logic/commands/searchmode/ExitSearchModeCommand.java, src/main/java/seedu/address/logic/commands/searchmode/InitSearchModeCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/contact/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/event/parser/EventAddAllCommandParser.java, src/test/java/seedu/address/logic/commands/event/commands/EventAddAllCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/event/parser/EventAddAllCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalEvents.java
1. From searchmode, user can type "add-all EVENT INDEX" to add all contacts from searchmode to the event. The current implementation adds the contact to all the roles of the event that he/she has. e.g. if Alice is both an attendee and sponsor, she will be added as both an attendee and sponsor to the event by default.
2. Changed the command word for "eventadd" back to "event-add"
3. Added short form for searchmode: "sm" and exitsearch: "es" for greater ease of manoeuvring in and out of searchmode.
=> Implement addall feature

src/main/java/seedu/address/logic/commands/contact/commands/EditCommand.java, src/main/java/seedu/address/model/event/Event.java, src/test/java/seedu/address/model/event/EventTest.java, src/test/java/seedu/address/testutil/TypicalEvents.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Edit command that changes a contact's role will now remove the contact from event if he or she no longer has that role
Fixes #149
=> Update edit command to remove contact from event role

src/main/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommand.java, src/main/java/seedu/address/logic/parser/SearchModeSearchCommandParser.java, src/test/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommandTest.java, src/test/java/seedu/address/logic/parser/SearchModeSearchCommandParserTest.java
Closes #198 , 
Closes #196 
Changes Searchmodesearch to throw a ParseException with invalid command if empty flag inputs are present
Change the user response message to show how many people were added on successful search and No persons found message on  no matching search
=> Change searchmodesearch to throw ParseException on empty input and change success messages

src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/ui/EventCard.java, src/main/java/seedu/address/ui/Observer.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/test/java/seedu/address/logic/commands/event/commands/FindEventCommandTest.java, src/test/java/seedu/address/model/event/EventTest.java, src/test/java/seedu/address/model/person/PersonTest.java
On find-event, the contacts displayed will now show only their event specific roles
Fixes #170
=> Update find event to show contacts with event specific roles

src/main/java/seedu/address/logic/parser/contact/parser/EditCommandParser.java, src/test/java/seedu/address/logic/parser/contact/parser/EditCommandParserTest.java
Previously, the `edit` command does not support the assigning of multiple roles to a person.
Now, a user can type a command to edit a person to have multiple roles.
For example, this command edits the person with `index 2` to take on the roles of `attendee`, `vendor` and `sponsor`.
```
edit 2 r/attendee r/vendor r/sponsor
```
Fixes #167
=> Implement assigning multiple roles to a Person when editing

src/main/java/seedu/address/model/util/SampleDataUtil.java
I have added 26 contacts, each one starting with a letter of the alphabet for ease of comparision
there are a mix of sponsors / vendors, attendees and volunteers
I think the exact roles / names can be altered over time if needed, but for now at least we have a "default" list of sponsors and vendors in our application.
fix #176
=> add sponsors and vendors to default contact list

src/main/resources/view/BrownTheme.css, src/main/resources/view/EventListCard.fxml
Fix #155 
Allow wrapping of Event Title for maximum of 3 lines
Examples:
=> Add wrapping for event title for 3 lines

src/main/java/seedu/address/logic/parser/ParserUtil.java
Changed error message for parseStringOfIndices to be more general as it is used for exclude as well
Closes #228
=> Changed parse exception message for parseStringOfIndice

src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java
Fixes #237 
The reason why the user sees the wrong error message is because there's a mismatch between the code that checks for duplicate persons and the error msg that prints out the reason for duplicate.
When checking for duplicates of 2 contacts based on telegram username, when either contact does not have a telegram username, then only their phone number and email need to be considered.
When printing out the error message, the code checks for telegram username equality even if either contact does not have a telegram username, and thus points out that 2 contacts are equal when they both do not have telegram usernames, represented by "null" and proceeds to show the wrong reason for duplication.
This PR attempts to fix this issue.
=> Fix bug where user is unable to add contact

src/main/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommand.java, src/main/java/seedu/address/model/person/predicates/TelegramContainsKeywordsPredicate.java, src/test/java/seedu/address/model/predicates/TelegramContainsKeywordPredicateTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #281
Fixes #272 
Search mode breaks down when a telegram username search is performed on contacts with no telegram username. This is because contacts with no telegram username have null as their telegram username field and calling a method on null leads to java.lang.reflect.invocationtargetexception.
This PR attempts to fix it by first checking if the contact has a telegram username. If the contact does not have a telegram username, then the predicate will immediately return false.
Furthermore, the error message when no contacts are found is made more general to accommodate the case when no contacts are found due to the contacts already existing in search results.
=> Fix searchmode bug

docs/UserGuide.md, src/main/java/seedu/address/model/person/TelegramUsername.java
- Fixes #245 
- Fixes #238 
I widened the error message to better reflect all the different constraints that could be leading to the input validation error.
So now, instead of just problem due to
- only alphanumeric and underscore
- 5 to 32 char
I widened the message to say that problem could be due to
- must start with alphabet
- only alphanumeric and underscore
- 5 to 32 char
I also added a note in the UG to reflect that Telegram Usernames must start with alphabet.
=> Fix telegram input validation constraint message to reflect true constraints

src/main/resources/view/PersonListCard.fxml
- Fixes #258 
Added minWdith to the Telegram username UI such that it is always on screen.
Added wrapping to the name such that it can wrap for 2 lines, but does not handle a really long name (meaning it still truncates)
=> Set minWidth for Telegram Username

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/event/commands/EventAddAllCommand.java, src/test/java/seedu/address/logic/commands/event/commands/EventAddAllCommandTest.java
Fixes #302 
Previously when adding contacts from search-mode using add-all command, when contact has no role, the result display does not say anything, in other words, it fails silently. 
This PR attempts to fix that by adding an error message when user tries to add contact with no role using add-all in search mode.
=> Fix add-all to show error when adding contact with no role

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/contact/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/FindNameCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/FindRoleCommand.java, src/main/java/seedu/address/logic/commands/contact/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/event/commands/AddEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/DeleteEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/FindEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java, src/main/java/seedu/address/logic/commands/searchmode/InitSearchModeCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/contact/commands/AddCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
An initial solution to #170 was done using an Observer pattern to update the Person Card with event-specific roles on find-event command.
However, due to JavaFX lazy evaluation and creation of PersonCard Object, there will be instances where Person does not have an Observer and is thus unable to update the Person Card to display event specific roles when find-event command is called. This results in the GUI occasionally rendering the contacts' general roles instead of their event specific roles, making it buggy and inconsistent.
In order to work around that, I have decided to use a new approach where I render from a different list of contacts specifically when there is a find-event command called, based on the boolean property isFindEvent. To follow up on that, I made execution of other …
=> Fix roles in event view

src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/predicates/PersonIsRolePredicate.java, src/main/java/seedu/address/model/person/predicates/PhoneNumberContainsKeywordPredicate.java, src/test/java/seedu/address/model/predicates/AddressContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/predicates/EmailContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/predicates/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/predicates/PhoneNumberContainsKeywordPredicateTest.java
Adds defensive checks for Predicates to prevent further search mode exceptions
Should not be necessary as those fields are checked but could improve code quality and mitigate future bugs
Use equality check rather an assertions as these could lead to errors in runtime if other checks fail
**EDIT: Seems to be allowed**
Will merge by tmr if no one has any issues with it
Should not violate feature freeze?
Fits under:
Can be allowed only if the current behavior causes the software to misbehave (i.e., crash, give incorrect results, store inconsistent data, or make it unusable for typical users).
and improving code quality
=> Predicate defensive programming

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java
Fixes #233, #247, #252, #306
The UG now contains more explanations for the commands so that users will have less ambuiguity regarding the behaviour of our app.
Additionally, the message usage for event-add command is corrected where before it says that it only accepts one contact index which is not correct (a bug), now it say that it can accept one or more contact indices.
=> Refine UG with more explanations and examples

src/main/java/seedu/address/logic/parser/event/parser/NewEventCommandParser.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/model/event/EventTest.java, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/NameTest.java
- Fixes #244 
Event names are restricted to 60 characters
Names are restricted to 100 characters
address and emails are restricted to 120 characters
=> Prevent truncation for event name, contact name, address, email

docs/UserGuide.md
Previously, the search mode section in the User Guide was missing the command `add-on` in the summary. This has been fixed.
Closes #259
=> Fill in missing search mode commands in User Guide

src/main/java/seedu/address/model/person/Phone.java, src/test/java/seedu/address/model/person/PhoneTest.java
Previously, we only set a lower bound to the length of the phone number of a Person. We enforced a minimum length of 3. However, there was no upper bound. This PR address the issue.
Closes #249
=> Fix Phone Number Bug

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java
All our commands will always specify the verb (e.g. `add`, `search`) at the front of the command.
However, `event-add` does not follow this convention. Hence, this PR changes it to `add-event`, and the corresponding short-form command has been changed from `ea` to `ae`.
Closes #257
=> Change command name for adding event

src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java
Changes the error message to better represent cases of invalid indices. Seems to be allowed according to the forum reply.
Closes #307
=> Widen remove error messages

src/main/java/seedu/address/logic/commands/contact/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommand.java, src/main/java/seedu/address/logic/commands/event/commands/RemovePersonFromEventCommand.java, src/test/java/seedu/address/logic/commands/contact/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/event/commands/AddPersonToEventCommandTest.java
There are instances where deleting a contact while viewing a list of contacts returned from find-event will cause the contacts' non-event specific roles to pop out, which is not intended. This PR aims to fix that by checking if the user had previous entered a find-event command and if so, update the list of contacts with event-specific roles only.
Another bug occurs when adding a contact to an event when the contact is already inside the event, but adding to another role after executing find-event, as the UI does not update to reflect that the contact has an additional event-specific role. This PR fixes that by creating a new list of contacts in the event with their updated roles and displaying these contacts.
Additionally, while in find-event of event A, if a user executes remove contact …
=> Fix event card display numbers and event specific roles
